spring:
  application:
    name: zuul-service

server:
  port: 8079
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
zuul:
  routes:
    producer:
      url: http://localhost:8080